import React, { useEffect, useState } from "react";
import { Dim, PhoneImage, Modal, CloseButton, NextButton, Title, Blurb, Img, Row, Minerals, Section, DropdownTitle, DropdownContent, ExpandButton, ScrollCont } from "../DRCPopUp/PopUpElements";
import Phone from "../../assets/phonecases/chile-phonecase.png";
import ThisImage from "../../assets/chile-img.jpg";

const ChilePopUp = ({ goToNext, setOpenPopup, location }) => {
  const [showModal, setShowModal] = useState(false);

  useEffect(() => {
    const timer = setTimeout(() => setShowModal(true), 1000);
    return () => clearTimeout(timer);
  }, []);

  const [expanded, setExpanded] = useState({
    conflict: false,
    labor: false,
    governance: false,
  });

  const toggleSection = (section) => {
    setExpanded((prevState) => ({
      ...prevState,
      [section]: !prevState[section],
    }));
  };

  return (
    <Dim>
      <PhoneImage src={Phone} alt={`Phone case for ${location.name}`} />
      {showModal && (
        <Modal>
          <CloseButton onClick={() => setOpenPopup(false)} />
          <NextButton
            onClick={() => {
              setOpenPopup(false);
              goToNext();
            }}
          />
          <Title>Mining in Chile</Title>
          
        <ScrollCont>
        <Blurb>
        Chile is a leading global producer of copper and lithium, two critical minerals used in the production of iPhones. Copper is essential for wiring and circuitry, while lithium powers the rechargeable batteries that drive mobile devices. Chile’s mining industry underpins global technology supply chains but faces challenges of environmental sustainability and equitable resource governance.
        </Blurb>
        <Row>
        <a href="https://www.mining-journal.com/data/news-analysis/4368940/copper-production-chile-climbs-august" target="_blank">
            <Img src={ThisImage} className="chile"></Img>
        </a>
        <Minerals>
            <ul>
            <li>
                <b>Copper:</b> Widely used in iPhone wiring and printed circuit boards for its excellent conductivity. Chile is the world’s largest copper producer, supplying over 25% of global demand, with mines concentrated in the Atacama Desert.
            </li>
            <li>
                <b>Lithium:</b> A key component of lithium-ion batteries, lithium enables long-lasting, rechargeable power in smartphones. Chile’s vast salt flats, particularly in the Salar de Atacama, host some of the richest lithium reserves globally.
            </li>
            </ul>
        </Minerals>
        </Row>
        <Section>
        <DropdownTitle onClick={() => toggleSection("conflict")}>
            Environmental Impacts and Global Supply Chains
            <ExpandButton>{expanded.conflict ? "-" : "+"}</ExpandButton>
        </DropdownTitle>
        {expanded.conflict && (
            <DropdownContent>
            <p>
                Chile’s role in mining critical minerals like copper and lithium ties its economy to global technology production but raises environmental and social concerns:
            </p>
            <ul>
                <li>
                <b>Water Scarcity:</b> Mining operations in arid regions like the Atacama Desert consume vast quantities of water, intensifying local water shortages and sparking conflict with Indigenous and farming communities.
                </li>
                <li>
                <b>Global Tech Dependence:</b> The demand for Chilean copper and lithium continues to rise as smartphone, electric vehicle, and renewable energy industries grow, making Chile a vital player in global supply chains.
                </li>
            </ul>
            </DropdownContent>
        )}
        </Section>

        <Section>
        <DropdownTitle onClick={() => toggleSection("labor")}>
            Labor and Economic Contributions
            <ExpandButton>{expanded.labor ? "-" : "+"}</ExpandButton>
        </DropdownTitle>
        {expanded.labor && (
            <DropdownContent>
            <ul>
                <li>
                <b>Employment in Mining:</b> The mining sector is a cornerstone of Chile’s economy, employing thousands of workers, particularly in rural and resource-rich regions.
                </li>
                <li>
                <b>Labor Strikes:</b> Strikes over wages and working conditions frequently occur in the mining sector, with workers demanding a fair share of the profits generated by the nation’s mineral wealth.
                </li>
                <li>
                <b>Indigenous Rights:</b> Mining often overlaps with Indigenous lands, leading to disputes over land use, resource rights, and environmental impact.
                </li>
            </ul>
            </DropdownContent>
        )}
        </Section>

        <Section>
        <DropdownTitle onClick={() => toggleSection("governance")}>
            Resource Governance and Sustainability
            <ExpandButton>{expanded.governance ? "-" : "+"}</ExpandButton>
        </DropdownTitle>
        {expanded.governance && (
            <DropdownContent>
            <ul>
                <li>
                <b>Environmental Regulations:</b> Efforts to manage the environmental impact of mining include stricter water usage controls and reclamation projects, though enforcement remains uneven.
                </li>
                <li>
                <b>State-Owned Mining:</b> Chile’s largest copper producer, Codelco, is state-owned, ensuring that a portion of mining profits contributes to national development. However, private companies dominate lithium production.
                </li>
                <li>
                <b>Global Demand Pressures:</b> As a major supplier of materials critical for smartphones and batteries, Chile faces challenges in balancing economic growth with environmental and social equity.
                </li>
            </ul>
            </DropdownContent>
        )}
        </Section>
        </ScrollCont>
        </Modal>
      )}
    </Dim>
  );
};

export default ChilePopUp;

